import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  SessionProvider  from "@/app/components/SessionProvider";
import { getServerSession } from "next-auth";
import AppBar from "./components/AppBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <AppBar/>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
